Update README.md
YOURLS/awesome pull request #165
Opened 2024-02-20 09:36 UTC by za22061991

Add new plugins (Keyword Limiter)

2024-02-20 10:07 UTC, dgw requested changes

2024-02-20 10:07 UTC, dgw commented on README.md
>  - [Keyword not found](https://github.com/8thwall/keyword-not-found-set-field-yourls) - If keyword isn't found in the database, redirect to admin page and pre-populate the short URL field.
New plugin should be added in alphabetical order above this entry

2024-02-20 21:22 UTC, dgw approved these changes
Thanks for re-sorting!

2024-02-21 11:06 UTC, LeoColomb approved these changes

2024-02-21 11:06 UTC, merged