added plugin YOURLS-Custom-Header name
YOURLS/awesome pull request #185
Opened 2024-11-28 15:48 UTC by srivastava07

This plugin enables the addition of a **custom header to the URL**, facilitating compliance with regulatory requirements in certain countries, such as India, for bulk SMS services. Pass `custom_header` in query param to add custom header as prefix to the generated short url

2024-11-28 18:19 UTC, LeoColomb requested changes
Thanks for submitting this pull request, @srivastava07.
Let's make the name a bit more readable.
Also, don't hesitate to add a license file to your project to ease its use and open it for contributions. https://github.com/srivastava07/YOURLS-Custom-Header/community/license/new?branch=main

2024-11-28 18:19 UTC, LeoColomb commented on README.md
> +- [YOURLS-Custom-Header](https://github.com/srivastava07/YOURLS-Custom-Header) - This plugin allows the addition of a custom header to the generated URL, enabling compliance with specific regulatory
```suggestion
- [Custom Header](https://github.com/srivastava07/YOURLS-Custom-Header) - This plugin allows the addition of a custom header to the generated URL, enabling compliance with specific regulatory requirements in certain countries, such as India, for bulk SMS services.
```

2024-11-29 04:17 UTC, srivastava07 commented
@LeoColomb I have added the LICENSE file, Thanks for the suggestion.

2024-11-29 04:34 UTC, dgw approved these changes
I don't understand how this prefix counts as a "header", but the addition here looks fine assuming that users who know (and need) what this does will recognize it in the list.

2024-11-29 10:02 UTC, LeoColomb approved these changes

2024-11-29 10:02 UTC, merged